apiVersion: v2
name: cluster-vsphere
description: A helm chart for creating Cluster API clusters with the vSphere provider (CAPV).
version: 8.0.0
home: https://github.com/giantswarm/cluster-vsphere
icon: https://s.giantswarm.io/app-icons/vsphere/2/icon-light.png
sources:
- https://github.com/giantswarm/cluster-vsphere
maintainers:
- name: Team Rocket
  email: team-rocket@giantswarm.io
keywords:
- capv
- vsphere
annotations:
  application.giantswarm.io/app-type: cluster
  application.giantswarm.io/team: rocket
restrictions:
  compatibleProviders:
  - vsphere
dependencies:
- repository: https://giantswarm.github.io/cluster-test-catalog
  name: cluster
  version: 7.0.1-dev.migrate-app--elmreleases.2026-08-04.14-15-21.h66e00d7
