apiServer:
  enableAdmissionPlugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,ResourceQuota,PersistentVolumeClaimResize,DefaultStorageClass,Priority,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook"
  featureGates: ""
  certSANs: []

cluster:
  kubernetesVersion: "v1.25.16"
  enableEncryptionProvider: true

clusterDescription: ""

clusterLabels: {}

controllerManager:
  featureGates: ""

controlPlane:
  replicas: 1
  machineTemplate:
    cloneMode: "linkedClone"
    diskGiB: 50
    numCPUs: 4
    template: "flatcar-stable-3602.2.1-kube-v1.25.16-gs"
    resourcePool: "*/Resources"
    memoryMiB: 8192
    network:
      devices:
      - dhcp4: true
        networkName: ""
  etcd:
    imageRepository: "gsoci.azurecr.io/giantswarm"
    imageTag: 3.5.4-0-k8s
  dns:
    imageRepository: "gsoci.azurecr.io/giantswarm"
    imageTag: 1.9.4-giantswarm
  image:
    repository: gsoci.azurecr.io/giantswarm
  resourceRatio: 8

global:
  connectivity:
    network:
      controlPlaneEndpoint:
        host: ""
        port: 6443
        ipPoolName: "wc-cp-ips"
      loadBalancers:
        cidrBlocks: []
        ipPoolName: "svc-lb-ips"
      pods:
        cidrBlocks:
        - "10.244.0.0/16"
      services:
        cidrBlocks:
        - "172.31.0.0/16"
    containerRegistries: {}
  metadata:
    preventDeletion: false
  podSecurityStandards:
    enforced: true

internal:
  ciliumNetworkPolicy:
    enabled: true
  teleport:
    proxyAddr: teleport.giantswarm.io:443
    version: 14.1.3
    enabled: true
  sandboxContainerImage:
    name: giantswarm/pause
    registry: gsoci.azurecr.io
    tag: "3.9"

kubectlImage:
  registry: gsoci.azurecr.io
  name: giantswarm/kubectl
  tag: 1.23.5

nodeClasses:
  default:
    cloneMode: "linkedClone"
    diskGiB: 50
    numCPUs: 6
    memoryMiB: 16896
    resourcePool: "*/Resources"
    template: "flatcar-stable-3602.2.1-kube-v1.25.16-gs"
    network:
      devices:
      - networkName: ""
        dhcp4: true

nodePools:
  worker:
    class: default
    replicas: 2

oidc:
  issuerUrl: ""
  caFile: ""
  clientId: ""
  usernameClaim: ""
  groupsClaim: ""
  usernamePrefix: ""

organization: ""

osUsers:
- name: "giantswarm"
  sudo: "ALL=(ALL) NOPASSWD:ALL"

proxy:
  secretName: ""
  enabled: false

servicePriority: "highest"

sshTrustedUserCAKeys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM4cvZ01fLmO9cJbWUj7sfF+NhECgy+Cl0bazSrZX7sU vault-ca@vault.operations.giantswarm.io

vcenter:
  datacenter: ""
  username: ""
  password: ""
  datastore: ""
  server: ""
  thumbprint: ""
  region: ""
  zone: ""
