global:
  metadata:
    description: "test cluster"
    name: "test"
    organization: "giantswarm"
  connectivity:
    containerRegistries:
      gsoci.azurecr.io:
        - endpoint: zot-test-1.golem.gaws.gigantic.io
          credentials:
            username: example
            password: xxxxx
      gsociprivate.azurecr.io:
        - endpoint: zot-test-2.golem.gaws.gigantic.io
          credentials:
            username: example
            password: yyyyy
    localRegistryCache:
      enabled: true
      mirroredRegistries:
        - gsoci.azurecr.io
        - gsociprivate.azurecr.io
    network:
      controlPlaneEndpoint:
        host: "10.10.222.241"
        port: 6443
      loadBalancers:
        cidrBlocks:
          - "10.10.222.224/30"
    baseDomain: k8s.test
  controlPlane:
    replicas: 1
    machineTemplate:
      cloneMode: "linkedClone"
      diskGiB: 25
      numCPUs: 2
      memoryMiB: 8192
      resourcePool: "grasshopper"
      network:
        devices:
          - networkName: 'grasshopper-capv'
            dhcp4: true
  nodePools:
    worker:
      replicas: 2
      cloneMode: "linkedClone"
      diskGiB: 25
      numCPUs: 2
      memoryMiB: 8192
      resourcePool: "grasshopper"
      network:
        devices:
          - networkName: 'grasshopper-capv'
            dhcp4: true
  providerSpecific:
    vcenter:
      server: "https://foo.example.com"
      username: "vcenter-admin"
      password: "vcenter-admin-password"
      datacenter: "Datacenter"
      datastore: "vsanDatastore"
      # openssl s_client -connect https://foo.example.com < /dev/null 2>/dev/null | openssl x509 -fingerprint -noout -in /dev/stdin
      thumbprint: "F7:CF:F9:E5:99:39:FF:C1:D7:14:F1:3F:8A:42:21:95:3B:A1:6E:16"
      region: "k8s-region"
      zone: "k8s-zone"
internal:
  enableEncryptionProvider: false
