apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-cloud-provider-vsphere
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.clusterDescription }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    giantswarm.io/service-priority: "{{ .Values.servicePriority }}"
    {{- include "labels.common" . | nindent 4 }}
spec:
  suspend: false # It can be unsuspended by the post-install/post-upgrade hook. Useful if we need to populate some fields later on.
  releaseName: cloud-provider-vsphere
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: cloud-provider-vsphere
      version: 1.5.0-48a19a71a2491785dc96c55f766c91d9545168ee
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-default-test
  dependsOn:
    - name: {{ include "resource.default.name" $ }}-cilium
      namespace: {{ $.Release.Namespace }}
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  interval: {{ ((.Values.helmReleases).cpi).interval | default "10m" }}
  install:
    remediation:
      retries: 30
  valuesFrom:
    - kind: Secret
      name: {{ include "credentialSecretName" $ }}
      valuesKey: "username"
      targetPath: "global.config.username"
    - kind: Secret
      name: {{ include "credentialSecretName" $ }}
      valuesKey: "escapedPassword"
      targetPath: "global.config.password"
  values:
    global:
      config:
        enabled: true
        clusterId: {{ include "resource.default.name" $ }}
        vcenter: "{{ .Values.vcenter.server }}"
        datacenter: "{{ .Values.vcenter.datacenter }}"
        region: "{{ .Values.vcenter.region }}"
        zone: "{{ .Values.vcenter.zone }}"
        thumbprint: "{{ .Values.vcenter.thumbprint }}"
    kube-vip-cloud-provider:
      cidrGlobal: '{{ join "," .Values.connectivity.network.loadBalancers.cidrBlocks }}'
