apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "resource.default.name" $ }}
  namespace: {{ .Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.global.metadata.description }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    giantswarm.io/service-priority: "{{ .Values.global.metadata.servicePriority }}"
    {{- include "labels.common" . | nindent 4 }}
    {{- range $key, $val := .Values.global.metadata.labels }}
    {{ $key }}: {{ $val | quote }}
    {{- end}}
    {{- if .Values.global.podSecurityStandards.enforced }}
    policy.giantswarm.io/psp-status: disabled
    {{- end }}
    {{- include "preventDeletionLabel" $ | nindent 4 }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        {{- range .Values.connectivity.network.pods.cidrBlocks }}
        - {{ . }}
        {{- end }}
    services:
      cidrBlocks:
        {{- range .Values.connectivity.network.services.cidrBlocks }}
        - {{ . }}
        {{- end }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ include "resource.default.name" $ }}
    namespace: {{ .Release.Namespace }}
  infrastructureRef:
    apiVersion: {{ include "infrastructureApiVersion" . }}
    kind: VSphereCluster
    name: {{ include "resource.default.name" $ }}
    namespace: {{ .Release.Namespace }}
  paused: {{ include "isIpamEnabled" $ }}
