apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" $ }}-kubevip-pod
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  content: {{ include "kubevip" . | b64enc | quote }}
