apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resource.default.name" $ }}-kubevip-pod
  labels:
    {{- include "labels.common" . | nindent 4 }}
stringData:
  content: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: kube-vip
      namespace: kube-system
    spec:
      initContainers:
      - name: update-hosts-record
        image: gsoci.azurecr.io/giantswarm/busybox:1.37.0
        command: ["/bin/sh", "-c", "echo '127.0.0.1  kubernetes' >> /etc/hosts"]
      containers:
      - args:
        - manager
        env:
        - name: cp_enable
          value: "true"
        - name: svc_enable
          value: "false"
        - name: prometheus_server
          value: ":2113"
        - name: vip_arp
          value: "true"
        - name: vip_leaderelection
          value: "true"
        - name: vip_address
          value: {{ .Values.global.connectivity.network.controlPlaneEndpoint.host }}
        - name: vip_cidr
          value: "32"
        - name: vip_interface
          value: ens192
        - name: vip_leaseduration
          value: "15"
        - name: vip_renewdeadline
          value: "10"
        - name: vip_retryperiod
          value: "2"
        image: gsoci.azurecr.io/giantswarm/kube-vip:v0.9.0
        imagePullPolicy: IfNotPresent
        name: kube-vip
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_TIME
        volumeMounts:
        - mountPath: /etc/kubernetes/admin.conf
          name: kubeconfig
      hostAliases:
      - hostnames:
        - kubernetes
        ip: 127.0.0.1
      hostNetwork: true
      volumes:
      - hostPath:
          path: /etc/kubernetes/super-admin.conf # this is reverted to admin.conf by a postKubeadmCommand
          type: FileOrCreate
        name: kubeconfig
    status: {}
