# kubectl apply -f https://raw.githubusercontent.com/kube-vip/kube-vip-cloud-provider/main/manifest/kube-vip-cloud-controller.yaml 
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: {{ include "resource.default.name" $ }}-kubevip-cloud-provider
  namespace: {{ $.Release.Namespace }}
  annotations:
    cluster.giantswarm.io/description: "{{ .Values.clusterDescription }}"
  labels:
    cluster-apps-operator.giantswarm.io/watching: ""
    giantswarm.io/service-priority: "{{ .Values.servicePriority }}"
    {{- include "labels.common" . | nindent 4 }}
spec:
  releaseName: kubevip-cloud-provider
  targetNamespace: kube-system
  storageNamespace: kube-system
  chart:
    spec:
      chart: kube-vip-cloud-provider
      version: 0.4.3
      sourceRef:
        kind: HelmRepository
        name: {{ include "resource.default.name" $ }}-kubevip
  kubeConfig:
    secretRef:
      name: {{ include "resource.default.name" $ }}-kubeconfig
  interval: 10m
  install:
    remediation:
      retries: 30
  # Default values
  # https://github.com/kube-vip/helm-charts/blob/kube-vip-0.4.3/charts/kube-vip-cloud-provider/values.yaml
  values:
