apiVersion: v1
kind: Secret
metadata:
  name: {{ include "credentialSecretName" $ }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
  annotations: # this will be deleted by cluster-api-cleaner-vsphere controller
    helm.sh/resource-policy: "keep"
data:
  username: {{ .Values.vcenter.username | b64enc | quote }}
  password: {{ .Values.vcenter.password | b64enc | quote }}
  # https://github.com/fluxcd/flux2/issues/2625
  escapedPassword: {{ .Values.vcenter.password | replace "." "\\." | replace "," "\\," | b64enc | quote }}
