apiVersion: v1
kind: Secret
metadata:
  name: {{ include "credentialSecretName" $ }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
data:
  username: {{ .Values.global.providerSpecific.vcenter.username | b64enc | quote }}
  password: {{ .Values.global.providerSpecific.vcenter.password | b64enc | quote }}
  # https://github.com/fluxcd/flux2/issues/2625
  escapedPassword: {{ .Values.global.providerSpecific.vcenter.password | replace "\" "\\" | replace "\" "\\" | replace "." "\\." | replace "," "\\," | b64enc | quote }}
