apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereCluster
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" $ }}
  namespace: {{ .Release.Namespace }}
spec:
  controlPlaneEndpoint:
    host: {{ .Values.controlPlane.endpoint.host }}
    port: {{ .Values.controlPlane.endpoint.port }}
  identityRef:
    kind: Secret
    name: {{ include "resource.default.name" $ }}
  server: {{ .Values.vcenter.server }}
  thumbprint: {{ .Values.vcenter.thumbprint }}
