apiVersion: {{ include "infrastructureApiVersion" . }}
kind: VSphereClusterIdentity
metadata:
  name: {{ include "resource.default.name" $ }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  allowedNamespaces:
    selector:
      matchExpressions:
      - key: giantswarm.io/ignored-by-capv
        operator: DoesNotExist
  # Secret needs to be in the same namespace as the CAPV controller
  secretName: {{ ((.Values.userContext).secretRef).secretName }}
