---
apiVersion: {{ include "infrastructureApiVersion" . }}
kind: VSphereMachineTemplate
metadata:
  name: {{ include "resource.default.name" $ }}-control-plane-{{ include "machineTemplateSpec.hash" (dict "data" (include "controlplane-vspheremachinetemplate-spec" $) "salt" $.Values.cluster.providerIntegration.hashSalt) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
spec:
  template:
    spec:
      {{- include "controlplane-vspheremachinetemplate-spec" $ | nindent 6 -}}

{{- range $nodePoolName, $value := include "createMapOfWorkerPoolSpecs" . | fromYaml }}
{{- $c := (merge (dict "currentPool"  $value) (deepCopy $.Values)) }}
---
apiVersion: {{ include "infrastructureApiVersion" . }}
kind: VSphereMachineTemplate
metadata:
  name: {{ include "resource.default.name" $ }}-{{ $nodePoolName }}-{{ include "mtRevision" $c }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
spec:
  template:
    spec:
      {{- include "mtSpec" $c | nindent 6 -}}

{{- end }}