---
apiVersion: {{ include "infrastructureApiVersion" . }}
kind: VSphereMachineTemplate
metadata:
  name: {{ include "resource.default.name" $ }}-control-plane-{{ include "cluster.data.hash" (dict "data" (include "controlplane-vspheremachinetemplate-spec" $) "salt" $.Values.cluster.providerIntegration.hashSalt) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
spec:
  template:
    spec:
      {{- include "controlplane-vspheremachinetemplate-spec" $ | nindent 6 -}}

{{- range $nodePoolName, $nodePool := include "createMapOfWorkerPoolSpecs" . | fromYaml }}
{{- $_ := set $ "nodePool" (dict "name" $nodePoolName "config" $nodePool) }}
---
apiVersion: {{ include "infrastructureApiVersion" . }}
kind: VSphereMachineTemplate
metadata:
  name: {{ include "resource.default.name" $ }}-{{ $.nodePool.name }}-{{ include "cluster.data.hash" (dict "data" (include "worker-vspheremachinetemplate-spec" $) "salt" $.Values.cluster.providerIntegration.hashSalt) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "labels.common" $ | nindent 4 }}
spec:
  template:
    spec:
      {{- include "worker-vspheremachinetemplate-spec" $ | nindent 6 -}}
{{- end }}
