apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: VSphereMachineTemplate
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" $ }}
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      {{- with .Values.template }}
      cloneMode: {{ .cloneMode }}
      diskGiB: {{ .diskGiB }}
      folder: {{ .folder }}
      memoryMiB: {{ .memoryMiB }}
      network:
        devices:
        - dhcp4: true
          networkName: {{ .networkName }}
      numCPUs: {{ .numCPUs }}
      resourcePool: {{ .resourcePool }}
      {{- with .storagePolicyName }}
      storagePolicyName: {{ . }}
      {{- end }}
      template: {{ .templateName }}
      {{- end }}
      {{- with .Values.vcenter }}      
      datacenter: {{ .datacenter }}
      datastore: {{ .datastore }}
      server: {{ .server }}
      thumbprint: {{ .thumbprint }}
      {{- end }}
