kind: ConfigMap
metadata:
  labels:
    app-operator.giantswarm.io/watching: "true"
  name: testing-user-values
  namespace: org-giantswarm
apiVersion: v1
data:
  values: |
    global:
      release:
        version: "29.1.0"
      metadata:
        description: "test cluster"
        name: "testing"
        organization: "giantswarm"
      connectivity:
        network:
          allowAllEgress: true
          controlPlaneEndpoint:
            host: ""
            ipPoolName: wc-cp-ips # GlobalInClusterIpPool used to allocate IP from
            port: 6443
          loadBalancers:
            ipPoolName: svc-lb-ips # GlobalInClusterIpPool used to allocate IP from
        baseDomain: test.gigantic.io
      controlPlane:
        replicas: 3
        machineTemplate:
          network:
            devices:
              - networkName: 'v500-data'
                dhcp4: true
          diskGiB: 40
          numCPUs: 4
          memoryMiB: 8196
          folder: "kube-nodes"
        oidc:
          issuerUrl: https://dex.testing.test.gigantic.io
          clientId: "dex-k8s-authenticator"
          usernameClaim: "email"
          groupsClaim: "groups"
      nodePools:
        worker:
          diskGiB: 40
          folder: kube-nodes
          memoryMiB: 10240
          network:
            devices:
              - networkName: v500-data
                dhcp4: true
          numCPUs: 6
          replicas: 3
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: cluster-vsphere
  name: testing
  namespace: org-giantswarm
spec:
  catalog: cluster
  kubeConfig:
    inCluster: true
  name: cluster-vsphere
  namespace: org- giantswarm
  userConfig:
    configMap:
      name: testing-user-values
      namespace: org-giantswarm
    secret:
      name: vsphere-credentials
      namespace: org-giantswarm
  version: ""

