kind: ConfigMap
metadata:
  labels:
    app-operator.giantswarm.io/watching: "true"
  name: testing-user-values
  namespace: org-multi-project
apiVersion: v1
data:
  values: |
    global:
      metadata:
        description: "test cluster"
        organization: "multi-project"
      release: "27.0.0"
      connectivity:
        network:
          allowAllEgress: true
          controlPlaneEndpoint:
            host: ""
            ipPoolName: wc-cp-ips # auto allocated from this pool (GlobalInClusterIpPool crd). When left empty, no allocation is happening.
            port: 6443
          loadBalancers:
            cidrBlocks: [] # explicit cidr ranges 
            ipPoolName: svc-lb-ips # auto allocated from this pool (only 1 ip) When left empty, no allocation is happening.
        baseDomain: test.gigantic.io
      controlPlane:
        replicas: 3
        catalog: "giantswarm"
        machineTemplate:
          network:
            devices:
              - networkName: 'LS-GS-CAPV'
                dhcp4: true
          cloneMode: "linkedClone"
          diskGiB: 40
          numCPUs: 4
          memoryMiB: 8196
          resourcePool: "giantswarm"
          folder: "Giantswarm"
          template: flatcar-stable-3815.2.2-kube-v1.27.14-gs
        oidc:
          issuerUrl: https://dex.testing.test.gigantic.io
          caFile: ""
          clientId: "dex-k8s-authenticator"
          usernameClaim: "email"
          groupsClaim: "groups"
          usernamePrefix: ""
      nodeClasses:
        default:
          template: flatcar-stable-3815.2.2-kube-v1.27.14-gs
          cloneMode: "linkedClone"
          diskGiB: 40
          numCPUs: 6
          memoryMiB: 10240
          folder: "Giantswarm"
          resourcePool: "giantswarm"
          network:
            devices:
              - networkName: 'LS-GS-CAPV'
                dhcp4: true
    internal:
      enableEncryptionProvider: true
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: cluster-vsphere
  name: testing
  namespace: org-multi-project
spec:
  catalog: cluster
  kubeConfig:
    inCluster: true
  name: cluster-vsphere
  namespace: org-multi-project
  userConfig:
    configMap:
      name: testing-user-values
      namespace: org-multi-project
    secret:
      name: vsphere-credentials
      namespace: org-multi-project
  version: ""
---
apiVersion: v1
data:
  values: |
    clusterName: testing
    organization: giantswarm
    managementCluster: guppy
kind: ConfigMap
metadata:
  name: testing-default-apps-user-values
  namespace: org-multi-project
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  generation: 1
  labels:
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: default-apps-vsphere
    giantswarm.io/cluster: testing
    giantswarm.io/managed-by: cluster
  name: testing-default-apps
  namespace: org-multi-project
spec:
  catalog: cluster
  config:
    configMap:
      name: testing-cluster-values
      namespace: org-multi-project
  kubeConfig:
    inCluster: true
  name: default-apps-vsphere
  namespace: org-multi-project
  userConfig:
    configMap:
      name: testing-default-apps-user-values
      namespace: org-multi-project
  version: 0.14.0

