{{- if (include "isIpamSvcLoadBalancerEnabled" $) -}}
{{- range $i := until (int .Values.global.connectivity.network.loadBalancers.numberOfIps) }}
apiVersion: ipam.cluster.x-k8s.io/v1beta1
kind: IPAddressClaim
metadata:
  name: {{ include "lbClaimName" $ }}-{{$i}}
  labels:
    {{- include "ipamLabels" $ | nindent 4 }}
spec:
  poolRef:
    apiGroup: ipam.cluster.x-k8s.io
    kind: GlobalInClusterIPPool
    name: {{ $.Values.global.connectivity.network.loadBalancers.ipPoolName }}
{{- end }}
{{- end }}
