{{- if (include "isIpamControlPlaneIPEnabled" $) -}}
apiVersion: ipam.cluster.x-k8s.io/v1beta1
kind: IPAddressClaim
metadata:
  name: {{ include "resource.default.name" $ }}
  labels:
    {{- include "ipamLabels" $ | nindent 4 }}
spec:
  poolRef:
    apiGroup: ipam.cluster.x-k8s.io
    kind: GlobalInClusterIPPool
    name: {{ .Values.global.connectivity.network.controlPlaneEndpoint.ipPoolName }}
{{- end }}
